version: "3.8"

services:
  telegraf:
    image: docker.io/telegraf:latest
    container_name: telegraf
    restart: always
    env_file:
      - .env
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - internal
    depends_on:
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto.passwd:/mosquitto/config/mosquitto.passwd:rw
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - internal

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal
    depends_on:
      - mosquitto
      - telegraf

volumes:
  caddy_data:
  caddy_config:
  mosquitto_data:
  mosquitto_log:
    
networks:
  internal:
