# General
per_listener_settings false
allow_anonymous false
password_file /mosquitto/config/mosquitto.passwd

# Listener 1: Para tráfico que viene desde Caddy (WebSockets)
listener 9001
protocol websockets

# Listener 2: Para conexiones internas dentro de Docker (MQTT TCP estándar)
listener 1883
protocol mqtt

# Persistencia de datos en disco
persistence true
persistence_location /mosquitto/data/
log_dest stdout
