[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_offset = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  hostname = "chronos-iot"

# --- ENTRADA: Suscripción a los temas de Mosquitto ---
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "weather/#"
  ]
  qos = 0
  connection_timeout = "30s"
  username = "$MQTT_USERNAME"
  password = "$MQTT_PASSWORD"
  data_format = "json"

# --- SALIDA: Ejemplo enviando a la consola (para depuración) ---
[[outputs.file]]
  files = ["stdout"]
  data_format = "json"

[[outputs.influxdb_v2]]
  urls = ["https://us-east-1-1.aws.cloud2.influxdata.com"]  
  token = "$INFLUX_TOKEN"
  organization = "ulfar"
  bucket = "weather_station_sensors"

[[outputs.bigquery]]
  project = "fehura"
  dataset = "weather_station"
  credentials_file = "/etc/telegraf/gcp-sa.json"
